### ISSUE TITLE
Tilt Sensor Block Bug

### ISSUE THREAD

**Issue by wolbar** [blob8108/scratchblocks2#68]
The WeDo Tilt Sensor values reported for 'right' tilt, which should be a number 4, vacillate between 3 and 4 and stay there regardless of how the sensor is tilted. Programs work fine in Scratch 1.4, but not in Scratch 2.

Attached is an image of the program in Scratch 1.4 (works) and Scratch 2 (not works)

**Comment by blob8108** [comment]
I think you have the wrong place. Maybe try [LLK/scratch-flash](https://github.com/LLK/scratch-flash)?
