### ISSUE TITLE
Too much redirecting

### ISSUE THREAD

**Issue by luis140219** [blob8108/scratchblocks2#71]
I, when I want to exit via going Back, I need to do it 50000 times. That's bad. You should avoid this via avoiding any kind of URL change.

**Comment by blob8108** [comment]
This is the wrong place: see [scratchblocks.github.io](https://github.com/scratchblocks/scratchblocks.github.io) instead.

(The scratchblocks homepage has worked this way for a long time; any reason you only just noticed this?)

**Comment by luis140219** [comment]
I've gone to http://scratchblocks.github.io and noticed the issue.
