### ISSUE TITLE
Progressbars on diff move backwards

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [blob8108/scratchblocks2#73]
Despite the 10 second loading time for the average project, seeing the progressbar move backwards is really annoying.

The script should know the number of total assets already from the project JSON, so it is possible to make a progressbar that doesn't move backwards.

**Comment by blob8108** [comment]
I believe this behaviour is similar to how Phosphorus's progress bar works. The total project size in bytes can't be determined from the JSON alone, because we don't know the size of each asset.

And to be honest, the diff tool has many other more urgent problems anyway.

**Comment by MegaApuTurkUltra** [comment]
But it's bad UX design! Why not just show progress like scratch does, based on loaded asset count vs total asset count? Progressbars don't need to move at a constant speed anyway (it's more important to keep them from moving backwards). Can I send a pull req?
